# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actuator.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'actuator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63tuator.proto\x12\x08\x61\x63tuator\"Z\n\x10\x41\x63tuationCommand\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0f\n\x07turn_on\x18\x04 \x01(\x08\x32Q\n\x08\x41\x63tuator\x12\x45\n\x07\x45xecute\x12\x1a.actuator.ActuationCommand\x1a\x1a.actuator.ActuationCommand(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actuator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTUATIONCOMMAND']._serialized_start=28
  _globals['_ACTUATIONCOMMAND']._serialized_end=118
  _globals['_ACTUATOR']._serialized_start=120
  _globals['_ACTUATOR']._serialized_end=201
# @@protoc_insertion_point(module_scope)
