# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprocessor.proto\x12\tprocessor\"B\n\x0bTemperature\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"F\n\rProcessedData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32T\n\tProcessor\x12G\n\x0fProcessReadings\x12\x16.processor.Temperature\x1a\x18.processor.ProcessedData(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATURE']._serialized_start=30
  _globals['_TEMPERATURE']._serialized_end=96
  _globals['_PROCESSEDDATA']._serialized_start=98
  _globals['_PROCESSEDDATA']._serialized_end=168
  _globals['_PROCESSOR']._serialized_start=170
  _globals['_PROCESSOR']._serialized_end=254
# @@protoc_insertion_point(module_scope)
