# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sensor_pb2 as sensor__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorStub(object):
    """Serviço de streaming de leituras de temperatura
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamReadings = channel.unary_stream(
                '/sensor.Sensor/StreamReadings',
                request_serializer=sensor__pb2.ReadingRequest.SerializeToString,
                response_deserializer=sensor__pb2.Temperature.FromString,
                _registered_method=True)


class SensorServicer(object):
    """Serviço de streaming de leituras de temperatura
    """

    def StreamReadings(self, request, context):
        """Client envia um sensor_id e recebe um stream de leituras
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamReadings': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReadings,
                    request_deserializer=sensor__pb2.ReadingRequest.FromString,
                    response_serializer=sensor__pb2.Temperature.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensor.Sensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensor.Sensor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sensor(object):
    """Serviço de streaming de leituras de temperatura
    """

    @staticmethod
    def StreamReadings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensor.Sensor/StreamReadings',
            sensor__pb2.ReadingRequest.SerializeToString,
            sensor__pb2.Temperature.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
